baseURL = 'https://example.org/'
languageCode = 'en-US'
title = 'Hello World'

#-------------------------------[ANCHOR MENUS]--
[[menus.main]]
name = "Home"
url = "/#home"
weight = 10

[[menus.main]]
name = "About"
url = "/#about"
weight = 20

[[menus.main]]
name = "Journey"
url = "/#journey"
weight = 30

[[menus.main]]
name = "Skill"
url = "/#skills"
weight = 40

[[menus.main]]
name = "Projects"
url = "/#projects"
weight = 50

[[menus.main]]
name = "Testimony"
url = "/#testimony"
weight = 60

[[menus.main]]
name = "Service"
url = "/#service"
weight = 70

#-------------------------------[MENUS]--
[[menus.main]]
name = 'Posts'
pageRef = '/posts'
weight = 80

[[menus.main]]
name = 'Books'
pageRef = '/books'
weight = 90

[[menus.main]]
name = 'Tags'
pageRef = '/tags'
weight = 100

[[menus.main]]
name = 'Categories'
pageRef = '/categories'
weight = 110

#-------------------------------[MODULES]--
[markup.goldmark.renderer]
unsafe = true

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
